### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by machinedgod** [fischerling/vis-lspc#1]
Hey there,
I'd like to help you with this project. The issues are empty, would you mind creating some so I can try and implement them?

**Comment by fischerling** [comment]
Hey, thanks for your support.
I will think about current quirks and stuff that should be adressed.
All my usecases are implemented. And this is the first time I use a language server so no idea what people actually expect.

**Comment by fischerling** [comment]
@machinedgod I opened a bunch of issues that came to my mind.
Someare about implementation details some more for further discussion.
Feel free to open additional issues and hack on what ever you like.

**Comment by machinedgod** [comment]
No problem, I'll grab some for this weekend!
LSP is basically the only thing I miss from vis, so thank you for starting this project.
