### ISSUE TITLE
/proc/self/stat does not exist on macOS

### ISSUE THREAD

**Issue by erf** [fischerling/vis-lspc#10]
is there an alternative maybe to make it run on macOS?

**Comment by erf** [comment]
maybe:
```
pgrep -o -x vis
```

**Comment by fischerling** [comment]
> pgrep -o -x vis

I am not convinced that using the last started vis process will always be correct
but as a fallback for systems where `/proc/self/pid` is not present I think it is
definitely good enough.

**Comment by erf** [comment]
Is there another way perhaps to get the current process id?

**Comment by fischerling** [comment]
Hm using POSIX `getpid()` of course but I don't want to introduce lua posix as a dependency just to call `getpid()`.

An for now I think your suggestion using pgrep is definitly good enough.
But if you can come up with a even better solution it will always be welcome :)

**Comment by erf** [comment]
macOS also have `getpid()`, but if you want to use `pgrep` then we have to add a check for os

**Comment by erf** [comment]
i can add this

**Comment by fischerling** [comment]
macOS has `getpid()` because as far as I now macOS is POSIX compatible.

The way I did it now is that pgrep is the fallback if the linux interface `/proc/self/stat` is not present.
This should work for macOS, BSDs or maybe even cygwin.

**Comment by fischerling** [comment]
> i can add this

A sorry I already implemented it.

**Comment by fischerling** [comment]
Would you have a look as #11. please and verifiy that it does what we want on macOS?

Otherwise feel free to open a different PR with your solution ;)

**Comment by erf** [comment]
Ok, no problem. I was looking into using `uname` to get platform name, but your fallback method is probably better for now. I'll have a look.
