### ISSUE TITLE
lua-language-server does not answer our method calls

### ISSUE THREAD

**Issue by erf** [fischerling/vis-lspc#13]
I installed [lua-language-server](https://github.com/sumneko/lua-language-server) on macOS.

I then made a run script `lualsp` in `PATH` with the following:

```
(cd ~/projects/lua-language-server ; ./bin/macOS/lua-language-server -E ./main.lua )
```

Then i added the following to `visrc.lua`:

```
local lspc = require('plugins/vis-lspc')
lspc.ls_map.lua = {name = 'lua', cmd = 'lualsp'}
```

I then get the following `assertion` error:

```
vis-lspc/init.lua:492:
```

that is:
```
  local req = assert(ls.inflight[method_response.id])
```

Do you know what causes this? I'm i missing something?

**Comment by fischerling** [comment]
This asserts checks if the rpc method response received was actually issued.
When issuing a rpc call we remember the call in the inflight table of the language server.

Could you enable logging by setting `lspc.logging = true` and have a look or provide me with vis-lspc.log

**Comment by fischerling** [comment]
How did you install the language server?
Build it your self or is it available using luarocks?

**Comment by fischerling** [comment]
The problem is lua-language-server is the first language-server I encounter (it is the third at all) calling rpc methods from the client
which vis-lspc does not support yet.

**Comment by erf** [comment]
I followed the install procedure from this link: https://github.com/sumneko/lua-language-server/wiki/Build-and-Run-(Standalone)

Here is the log file:
[vis-lspc.log](https://github.com/fischerling/vis-lspc/files/6103586/vis-lspc.log)

**Comment by erf** [comment]
Not sure what you mean "calling rpc methods from the client", but then again i'm not sure how all of this works. But would be fun with more language support.

**Comment by fischerling** [comment]
505d1cdaea5fa6bdfd654ddd34bdfa85aa0ddb5d should fix the assert you encountered.
By adding an empty handler for method calls issued by the server.

The problem was a `workspace/configuration` method call from lua-language-server.
Specifying `workspace.configuration=false` in the client capabilities seams to get ignored by lua-language-server.

**Comment by erf** [comment]
I don't get the assertion error anymore. What is the simplest way to test if this works?

**Comment by fischerling** [comment]
> Not sure what you mean "calling rpc methods from the client", but then again i'm not sure how all of this works. But would be fun with more language support.

LSP is based on [json rpc](https://de.wikipedia.org/wiki/JSON-RPC) as simple way to invoke code execution on a remote.

LSP knows to three types of messages:

1. method calls - a json blob containing an `id` with an new id
2. method response - a json blob containing the `id` of a method call received earlier
3. notifications - a json blob without an `id` field. Therefore a notification can not be answered

We currently on send method calls to the language server and parsed and acted upon receiving
method responses.
But lua-language-server send us a method calls (`workspace/configuration`) which we did
not expect and do not support yet.

The asserts was ensuring the expectation that all messages containing an `id` field
correspond to a method call we issued and ware therefore method responses.

This is my understanding of LSP which may be incorrect this is also the first time dealing
with LSP but I hope this was somewhat understandable and informative :)

**Comment by fischerling** [comment]
> I don't get the assertion error anymore. What is the simplest way to test if this works?

What do you mean by works?

Currently we vis-lspc supports `textDocument/completion`, `textDocument/references`, `textDocument/declaration` and friends.
All key bindings are defined at the end of init.lua

**Comment by erf** [comment]
Thanks for the explanation.

I tried a couple of the keybindings, but nothing happened. Maybe there is something wrong with my keybindings..

**Comment by fischerling** [comment]
> Thanks for the explanation.
> 
> I tried a couple of the keybindings, but nothing happened. Maybe there is something wrong with my keybindings..

Hm now we call the methods like expected but lua-language-server is not answering at least on my system :(

**Comment by erf** [comment]
Here is a new log file, i tried to autocomplete, nothing happened, then i undo, and i got a message saying that the language server exited.

[vis-lspc.log](https://github.com/fischerling/vis-lspc/files/6103828/vis-lspc.log)

**Comment by erf** [comment]
Maybe i should try another language server..

**Comment by fischerling** [comment]
I am sorry that you have to struggle that hard!
The two language servers I tried clangd and python-language-server worked without hot fixing everything

**Comment by fischerling** [comment]
In the log lua-language-server writes I only see our 'initialize' message and nothing afterwards but I am sure that we send methods calls because they appear in the vis-lspc log

**Comment by erf** [comment]
Ok, no worries! I will look into it later and let you know if i get up and running.

**Comment by fischerling** [comment]
So I think I solved the mystery of the silent lua-language-server.
The answer is rather trivially and I am just stupid.
The original problem was that we crash if someone calls a method from lspc
via jsonrpc. My "brilliant" fix of just ignoring the message is the cause
why the language-server does not answer our method calls because it is still
waiting for a response from lspc.

This is fixed by answering all method calls with an `MethodNotFound` error.
Now lua-language-server seems to at least communicate with us.
