### ISSUE TITLE
Auto completion is wonky

### ISSUE THREAD

**Issue by fischerling** [fischerling/vis-lspc#16]

**Comment by jgarte** [comment]
What is the state of auto completion in `vis-lspc`? 

What are the things that you feel are missing from the implementation?

**Comment by fischerling** [comment]
Not quite sure. I don't use the feature that often.

What is your experience?

And do you need to save the file before issuing auto-completion?

**Comment by jgarte** [comment]
> Not quite sure. I don't use the feature that often.

@fischerling What are the features you use the most with `vis-lspc`?
 
> What is your experience?

Completion works great with jedi-language-server.

Sorry, is there a difference between completion and auto-completion?

I just want to make sure we're talking about the same thing.

> 
> And do you need to save the file before issuing auto-completion?

No, I don't need to save.

**Comment by fischerling** [comment]
> > Not quite sure. I don't use the feature that often.
> 
> @fischerling What are the features you use the most with `vis-lspc`?

Actually I use vis-lspc as a fancy replacement for ctags most of the time.
So only source code navigation with `textDocument/definition` and sometimes I use completions.
 
> > What is your experience?
> 
> Completion works great with jedi-language-server.
> 
> Sorry, is there a difference between completion and auto-completion?

Hm I can't remember why I used "Auto completion" in the issue's title.
What I mean is the LSP function `textDocument/completion` triggered by `Ctrl+Space` or `:lspc-completion`.
 
> I just want to make sure we're talking about the same thing.
> 
> > And do you need to save the file before issuing auto-completion?
> 
> No, I don't need to save.

A good to hear. With clangd I have to save the document before the completions are usable but maybe that because C/C++ has to be compiled and clangd may read the actual file from disk instead of relying on the `textDocument/didChange` messages from the LSP client.

**Comment by fischerling** [comment]
Moved to [https://gitlab.com/muhq/vis-lspc/-/issues/16](https://gitlab.com/muhq/vis-lspc/-/issues/16).
