### ISSUE TITLE
error after installation

### ISSUE THREAD

**Issue by FaradayAwerty** [fischerling/vis-lspc#18]
after requiring the plugin I get a window every time I run vis, in which there is this: 
~/.config/vis/plugins/vis-lspc/init.lua:20: attempt to index a nil value (upvalue 'lspc')

**Comment by fischerling** [comment]
Do you have vis with the [communicate API](https://github.com/martanne/vis/pull/675) installed?
I assume not.

But thanks for the report I will fix this and hopefully you should see a meaningful error message in the near future :)

**Comment by fischerling** [comment]
Fixed in 6549f12af82dcf3fc204a0e2e5caf60acc7af477.
