### ISSUE TITLE
Add more language server configurations

### ISSUE THREAD

**Issue by fischerling** [fischerling/vis-lspc#2]
## Background

vis-lspc starts an communicates with language servers via `vis:communicate` which is currently [not merged](https://github.com/martanne/vis/pull/675) into vis.
Communication is done by writing to the language servers stdin and receiving LSP messages on stdout.

There exists a configuration table `lspc.ls_map` which maps language server configurations, consisting of their name and a command line to start them, to their supported languages.

vis-lspc uses this configuration table to start a new language server.

Currently only clangd is in this map because it is the only language server implementation I use.

We should probably test and configure more language servers.

## Language server implementations

[Microsoft's list of language servers](https://microsoft.github.io/language-server-protocol/implementors/servers/)

### Configured by default

* clangd
* pyls (python-language-server, configured but not really testet)

**Comment by fischerling** [comment]
Maybe we can extract some language server configurations from neovim's [lspconfig-plugin](https://github.com/neovim/nvim-lspconfig)

**Comment by erf** [comment]
Maybe [Lua-lsp](https://github.com/Alloyed/lua-lsp) would be a nice place to start as we use it quite a bit ;) (have not tested it yet..)

**Comment by fischerling** [comment]
Aparantly https://github.com/pappasam/jedi-language-server works fine.

#25 thanks for testing and the configuration snippet @jgarte.

**Comment by jgarte** [comment]
> Aparantly https://github.com/pappasam/jedi-language-server works fine.
> 
> #25 thanks for testing and the configuration snippet @jgarte.

jedi-language-server runs way faster for completions than python-language-server or python-lsp-server (newer fork).

With jedi-language-server I tested library completion (methods, etc...), and file completion (using skim to fuzzy choose file names in the current working directory instead of vis-complete shell script).

**Comment by jgarte** [comment]
Ok, I tested haskell-language-server. Completion works!

```
local lspc = require('plugins/vis-lspc')

if next(lspc) then
    lspc.ls_map.python = {name = 'python', cmd = 'jedi-language-server'}
    lspc.ls_map.haskell = {name = 'haskell', cmd = 'haskell-language-server-wrapper --lsp'}
end

```

**Comment by jgarte** [comment]
I tried `gopls`:

```
 ~/go-play λ cat vis-lspc.log
LSPC Sending: Content-Length: 181

{"jsonrpc":"2.0", "params":{"client":{"version":"0.1.3", "name":"vis-lspc"}, "processID":28944, "capabilities":{"workspace":{"configuration":false}}}, "id":0, "method":"initialize"}
LS response(STDOUT): Content-Length: 2945

{"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{}},"completionProvider":{"triggerCharacters":["."],"completionItem":{}},"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"codeActionProvider":true,"codeLensProvider":{},"documentLinkProvider":{},"workspaceSymbolProvider":true,"documentFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":""},"renameProvider":true,"foldingRangeProvider":true,"executeCommandProvider":{"commands":["gopls.add_dependency","gopls.add_import","gopls.apply_fix","gopls.check_upgrades","gopls.gc_details","gopls.generate","gopls.generate_gopls_mod","gopls.go_get_package","gopls.list_known_packages","gopls.regenerate_cgo","gopls.remove_dependency","gopls.run_tests","gopls.start_debuggin
LS response(STDOUT): g","gopls.test","gopls.tidy","gopls.toggle_gc_details","gopls.update_go_sum","gopls.upgrade_dependency","gopls.vendor","gopls.workspace_metadata"]},"callHierarchyProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":"workspace/didChangeWorkspaceFolders"}}},"serverInfo":{"name":"gopls","version":"{\"path\":\"golang.org/x/tools/gopls\",\"version\":\"(devel)\",\"deps\":[{\"path\":\"github.com/BurntSushi/toml\",\"version\":\"v0.3.1\",\"sum\":\"h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=\"},{\"path\":\"github.com/google/go-cmp\",\"version\":\"v0.5.6\",\"sum\":\"h1:BKbKCqvP6I+rmFHt06ZmyQtvB8xAkWdhFyr0ZUNZcxQ=\"},{\"path\":\"github.com/sergi/go-diff\",\"version\":\"v1.1.0\",\"sum\":\"h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=\"},{\"path\":\"golang.org/x/mod\",\"version\":\"v0.4.2\",\"sum\":\"h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=\"},{\"path\":\"golang.org/x/sync\",\"version\":\"v0.0.0-20210220032951-036812b2e83c\",\"sum\":\"h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV8
LS response(STDOUT): 6Y7SQ=\"},{\"path\":\"golang.org/x/sys\",\"version\":\"v0.0.0-20210809222454-d867a43fc93e\",\"sum\":\"h1:WUoyKPm6nCo1BnNUvPGnFG3T5DUVem42yDJZZ4CNxMA=\"},{\"path\":\"golang.org/x/text\",\"version\":\"v0.3.6\",\"sum\":\"h1:aRYxNxv6iGQlyVaZmk6ZgYEDa+Jg18DxebPSrd6bg1M=\"},{\"path\":\"golang.org/x/tools\",\"version\":\"v0.1.8-0.20211014194737-fc98fb2abd48\",\"sum\":\"h1:hk7xRoeg0CG1nRLsd5BZLDUgVpA9bnKylGk1p2/BPH0=\"},{\"path\":\"golang.org/x/xerrors\",\"version\":\"v0.0.0-20200804184101-5ec99f83aff1\",\"sum\":\"h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=\"},{\"path\":\"honnef.co/go/tools\",\"version\":\"v0.2.0\",\"sum\":\"h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=\"},{\"path\":\"mvdan.cc/gofumpt\",\"version\":\"v0.1.1\",\"sum\":\"h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=\"},{\"path\":\"mvdan.cc/xurls/v2\",\"version\":\"v2.3.0\",\"sum\":\"h1:59Olnbt67UKpxF1EwVBopJvkSUBmgtb468E4GVWIZ1I=\"}]}"}},"id":0}
LSPC Sending: Content-Length: 41

{"jsonrpc":"2.0", "method":"initialized"}
LSPC Sending: Content-Length: 242

{"jsonrpc":"2.0", "params":{"textDocument":{"languageId":"go", "text":"package main\n  \nimport \"fmt\"\n  \nfunc main() {\n  \n    fmt.P\n}", "uri":"file:\/\/\/home\/jgart\/go-play\/hello.go", "version":0}}, "method":"textDocument\/didOpen"}
send didChange
LSPC Sending: Content-Length: 246

{"jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/go-play\/hello.go", "version":1}, "contentChanges":[{"text":"package main\n  \nimport \"fmt\"\n  \nfunc main() {\n  \n    fmt.P\n}"}]}, "method":"textDocument\/didChange"}
LSPC Sending: Content-Length: 179

{"jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/go-play\/hello.go"}, "position":{"line":6, "character":9}}, "id":1, "method":"textDocument\/completion"}
LS response(STDOUT): Content-Length: 99

{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":4,"message":"Loading packages..."}}Content-Length: 144

{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":3,"message":"Error loading packages: addView called before server initialized"}}Content-Length: 227

{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":1,"message":"Error loading workspace folders (expected 1, got 0)\nfailed to load view for file:///home/jgart/go-play: addView called before server initialized\n"}}Content-Length: 75

{"jsonrpc":"2.0","error":{"code":0,"message":"no views in session"},"id":1}
LSPC Error: no views in session (0) occurred during textDocument/completion
LSPC Sending: Content-Length: 130

{"jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/go-play\/hello.go"}}, "method":"textDocument\/didSave"}
LSPC Sending: Content-Length: 131

{"jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/go-play\/hello.go"}}, "method":"textDocument\/didClose"}
```


# Config

```
local lspc = require('plugins/vis-lspc')

if next(lspc) then
    lspc.ls_map.go = {name = 'go', cmd = 'gopls'}
end

```

**Comment by fischerling** [comment]
> I tried `gopls` with no luck:
> 
> ```
>  ~/go-play λ cat vis-lspc.log
> LSPC Sending: Content-Length: 181
> 
> {"jsonrpc":"2.0", "params":{"client":{"version":"0.1.3", "name":"vis-lspc"}, "processID":28944, "capabilities":{"workspace":{"configuration":false}}}, "id":0, "method":"initialize"}
> LS response(STDOUT): Content-Length: 2945
> 
> {"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{}},"completionProvider":{"triggerCharacters":["."],"completionItem":{}},"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"codeActionProvider":true,"codeLensProvider":{},"documentLinkProvider":{},"workspaceSymbolProvider":true,"documentFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":""},"renameProvider":true,"foldingRangeProvider":true,"executeCommandProvider":{"commands":["gopls.add_dependency","gopls.add_import","gopls.apply_fix","gopls.check_upgrades","gopls.gc_details","gopls.generate","gopls.generate_gopls_mod","gopls.go_get_package","gopls.list_known_packages","gopls.regenerate_cgo","gopls.remove_dependency","gopls.run_tests","gopls.start_debuggin
> LS response(STDOUT): g","gopls.test","gopls.tidy","gopls.toggle_gc_details","gopls.update_go_sum","gopls.upgrade_dependency","gopls.vendor","gopls.workspace_metadata"]},"callHierarchyProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":"workspace/didChangeWorkspaceFolders"}}},"serverInfo":{"name":"gopls","version":"{\"path\":\"golang.org/x/tools/gopls\",\"version\":\"(devel)\",\"deps\":[{\"path\":\"github.com/BurntSushi/toml\",\"version\":\"v0.3.1\",\"sum\":\"h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=\"},{\"path\":\"github.com/google/go-cmp\",\"version\":\"v0.5.6\",\"sum\":\"h1:BKbKCqvP6I+rmFHt06ZmyQtvB8xAkWdhFyr0ZUNZcxQ=\"},{\"path\":\"github.com/sergi/go-diff\",\"version\":\"v1.1.0\",\"sum\":\"h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=\"},{\"path\":\"golang.org/x/mod\",\"version\":\"v0.4.2\",\"sum\":\"h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=\"},{\"path\":\"golang.org/x/sync\",\"version\":\"v0.0.0-20210220032951-036812b2e83c\",\"sum\":\"h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV8
> LS response(STDOUT): 6Y7SQ=\"},{\"path\":\"golang.org/x/sys\",\"version\":\"v0.0.0-20210809222454-d867a43fc93e\",\"sum\":\"h1:WUoyKPm6nCo1BnNUvPGnFG3T5DUVem42yDJZZ4CNxMA=\"},{\"path\":\"golang.org/x/text\",\"version\":\"v0.3.6\",\"sum\":\"h1:aRYxNxv6iGQlyVaZmk6ZgYEDa+Jg18DxebPSrd6bg1M=\"},{\"path\":\"golang.org/x/tools\",\"version\":\"v0.1.8-0.20211014194737-fc98fb2abd48\",\"sum\":\"h1:hk7xRoeg0CG1nRLsd5BZLDUgVpA9bnKylGk1p2/BPH0=\"},{\"path\":\"golang.org/x/xerrors\",\"version\":\"v0.0.0-20200804184101-5ec99f83aff1\",\"sum\":\"h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=\"},{\"path\":\"honnef.co/go/tools\",\"version\":\"v0.2.0\",\"sum\":\"h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=\"},{\"path\":\"mvdan.cc/gofumpt\",\"version\":\"v0.1.1\",\"sum\":\"h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=\"},{\"path\":\"mvdan.cc/xurls/v2\",\"version\":\"v2.3.0\",\"sum\":\"h1:59Olnbt67UKpxF1EwVBopJvkSUBmgtb468E4GVWIZ1I=\"}]}"}},"id":0}
> LSPC Sending: Content-Length: 41
> 
> {"jsonrpc":"2.0", "method":"initialized"}
> LSPC Sending: Content-Length: 242
> 
> {"jsonrpc":"2.0", "params":{"textDocument":{"languageId":"go", "text":"package main\n  \nimport \"fmt\"\n  \nfunc main() {\n  \n    fmt.P\n}", "uri":"file:\/\/\/home\/jgart\/go-play\/hello.go", "version":0}}, "method":"textDocument\/didOpen"}
> send didChange
> LSPC Sending: Content-Length: 246
> 
> {"jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/go-play\/hello.go", "version":1}, "contentChanges":[{"text":"package main\n  \nimport \"fmt\"\n  \nfunc main() {\n  \n    fmt.P\n}"}]}, "method":"textDocument\/didChange"}
> LSPC Sending: Content-Length: 179
> 
> {"jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/go-play\/hello.go"}, "position":{"line":6, "character":9}}, "id":1, "method":"textDocument\/completion"}
> LS response(STDOUT): Content-Length: 99
> 
> {"jsonrpc":"2.0","method":"window/showMessage","params":{"type":4,"message":"Loading packages..."}}Content-Length: 144
> 
> {"jsonrpc":"2.0","method":"window/showMessage","params":{"type":3,"message":"Error loading packages: addView called before server initialized"}}Content-Length: 227
> 
> {"jsonrpc":"2.0","method":"window/showMessage","params":{"type":1,"message":"Error loading workspace folders (expected 1, got 0)\nfailed to load view for file:///home/jgart/go-play: addView called before server initialized\n"}}Content-Length: 75
> 
> {"jsonrpc":"2.0","error":{"code":0,"message":"no views in session"},"id":1}
> LSPC Error: no views in session (0) occurred during textDocument/completion
> LSPC Sending: Content-Length: 130
> 
> {"jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/go-play\/hello.go"}}, "method":"textDocument\/didSave"}
> LSPC Sending: Content-Length: 131
> 
> {"jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/go-play\/hello.go"}}, "method":"textDocument\/didClose"}
> ```
> 
> # Config
> ```
> local lspc = require('plugins/vis-lspc')
> 
> if next(lspc) then
>     lspc.ls_map.go = {name = 'go', cmd = 'gopls'}
> end
> ```

I also tried gopls some time ago.
Not sure if we can do something here.

**Comment by jgarte** [comment]
> > I tried `gopls` with no luck:
> > ```
> >  ~/go-play λ cat vis-lspc.log
> > LSPC Sending: Content-Length: 181
> > 
> > {"jsonrpc":"2.0", "params":{"client":{"version":"0.1.3", "name":"vis-lspc"}, "processID":28944, "capabilities":{"workspace":{"configuration":false}}}, "id":0, "method":"initialize"}
> > LS response(STDOUT): Content-Length: 2945
> > 
> > {"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{}},"completionProvider":{"triggerCharacters":["."],"completionItem":{}},"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"codeActionProvider":true,"codeLensProvider":{},"documentLinkProvider":{},"workspaceSymbolProvider":true,"documentFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":""},"renameProvider":true,"foldingRangeProvider":true,"executeCommandProvider":{"commands":["gopls.add_dependency","gopls.add_import","gopls.apply_fix","gopls.check_upgrades","gopls.gc_details","gopls.generate","gopls.generate_gopls_mod","gopls.go_get_package","gopls.list_known_packages","gopls.regenerate_cgo","gopls.remove_dependency","gopls.run_tests","gopls.start_debuggin
> > LS response(STDOUT): g","gopls.test","gopls.tidy","gopls.toggle_gc_details","gopls.update_go_sum","gopls.upgrade_dependency","gopls.vendor","gopls.workspace_metadata"]},"callHierarchyProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":"workspace/didChangeWorkspaceFolders"}}},"serverInfo":{"name":"gopls","version":"{\"path\":\"golang.org/x/tools/gopls\",\"version\":\"(devel)\",\"deps\":[{\"path\":\"github.com/BurntSushi/toml\",\"version\":\"v0.3.1\",\"sum\":\"h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=\"},{\"path\":\"github.com/google/go-cmp\",\"version\":\"v0.5.6\",\"sum\":\"h1:BKbKCqvP6I+rmFHt06ZmyQtvB8xAkWdhFyr0ZUNZcxQ=\"},{\"path\":\"github.com/sergi/go-diff\",\"version\":\"v1.1.0\",\"sum\":\"h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=\"},{\"path\":\"golang.org/x/mod\",\"version\":\"v0.4.2\",\"sum\":\"h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=\"},{\"path\":\"golang.org/x/sync\",\"version\":\"v0.0.0-20210220032951-036812b2e83c\",\"sum\":\"h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV8
> > LS response(STDOUT): 6Y7SQ=\"},{\"path\":\"golang.org/x/sys\",\"version\":\"v0.0.0-20210809222454-d867a43fc93e\",\"sum\":\"h1:WUoyKPm6nCo1BnNUvPGnFG3T5DUVem42yDJZZ4CNxMA=\"},{\"path\":\"golang.org/x/text\",\"version\":\"v0.3.6\",\"sum\":\"h1:aRYxNxv6iGQlyVaZmk6ZgYEDa+Jg18DxebPSrd6bg1M=\"},{\"path\":\"golang.org/x/tools\",\"version\":\"v0.1.8-0.20211014194737-fc98fb2abd48\",\"sum\":\"h1:hk7xRoeg0CG1nRLsd5BZLDUgVpA9bnKylGk1p2/BPH0=\"},{\"path\":\"golang.org/x/xerrors\",\"version\":\"v0.0.0-20200804184101-5ec99f83aff1\",\"sum\":\"h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=\"},{\"path\":\"honnef.co/go/tools\",\"version\":\"v0.2.0\",\"sum\":\"h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=\"},{\"path\":\"mvdan.cc/gofumpt\",\"version\":\"v0.1.1\",\"sum\":\"h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=\"},{\"path\":\"mvdan.cc/xurls/v2\",\"version\":\"v2.3.0\",\"sum\":\"h1:59Olnbt67UKpxF1EwVBopJvkSUBmgtb468E4GVWIZ1I=\"}]}"}},"id":0}
> > LSPC Sending: Content-Length: 41
> > 
> > {"jsonrpc":"2.0", "method":"initialized"}
> > LSPC Sending: Content-Length: 242
> > 
> > {"jsonrpc":"2.0", "params":{"textDocument":{"languageId":"go", "text":"package main\n  \nimport \"fmt\"\n  \nfunc main() {\n  \n    fmt.P\n}", "uri":"file:\/\/\/home\/jgart\/go-play\/hello.go", "version":0}}, "method":"textDocument\/didOpen"}
> > send didChange
> > LSPC Sending: Content-Length: 246
> > 
> > {"jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/go-play\/hello.go", "version":1}, "contentChanges":[{"text":"package main\n  \nimport \"fmt\"\n  \nfunc main() {\n  \n    fmt.P\n}"}]}, "method":"textDocument\/didChange"}
> > LSPC Sending: Content-Length: 179
> > 
> > {"jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/go-play\/hello.go"}, "position":{"line":6, "character":9}}, "id":1, "method":"textDocument\/completion"}
> > LS response(STDOUT): Content-Length: 99
> > 
> > {"jsonrpc":"2.0","method":"window/showMessage","params":{"type":4,"message":"Loading packages..."}}Content-Length: 144
> > 
> > {"jsonrpc":"2.0","method":"window/showMessage","params":{"type":3,"message":"Error loading packages: addView called before server initialized"}}Content-Length: 227
> > 
> > {"jsonrpc":"2.0","method":"window/showMessage","params":{"type":1,"message":"Error loading workspace folders (expected 1, got 0)\nfailed to load view for file:///home/jgart/go-play: addView called before server initialized\n"}}Content-Length: 75
> > 
> > {"jsonrpc":"2.0","error":{"code":0,"message":"no views in session"},"id":1}
> > LSPC Error: no views in session (0) occurred during textDocument/completion
> > LSPC Sending: Content-Length: 130
> > 
> > {"jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/go-play\/hello.go"}}, "method":"textDocument\/didSave"}
> > LSPC Sending: Content-Length: 131
> > 
> > {"jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/go-play\/hello.go"}}, "method":"textDocument\/didClose"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > # Config
> > ```
> > local lspc = require('plugins/vis-lspc')
> > 
> > if next(lspc) then
> >     lspc.ls_map.go = {name = 'go', cmd = 'gopls'}
> > end
> > ```
> 
> I also tried gopls some time ago. Not sure if we can do something here.

Is it an issue similar to #23 ?

**Comment by fischerling** [comment]
Maybe, maybe not.

I did not look at the gopls code to find the errors and find the reason for the crashes and especially if we are doing something wrong.
But I suspect that we are just doing something unexpected what VS Code or the other LSP-clients are not doing.

**Comment by mcepl** [comment]
`pyls` [project](https://github.com/palantir/python-language-server) is dead, it has been replaced by `pylsp` https://github.com/python-lsp/python-lsp-server and its server is called `pylsp` not just `pyls`.

**Comment by fischerling** [comment]
> `pyls` [project](https://github.com/palantir/python-language-server) is dead, it has been replaced by `pylsp` https://github.com/python-lsp/python-lsp-server and its server is called `pylsp` not just `pyls`.

Thanks I tested pylsp briefly and made it the default with 0fb192f2e78a61718832e07c98b72c00d137ea57 since `pyls` had no commits for one year.

**Comment by fischerling** [comment]
Moved to [https://gitlab.com/muhq/vis-lspc/-/issues/2](https://gitlab.com/muhq/vis-lspc/-/issues/2).
