### ISSUE TITLE
When using pyls: attempt to call a string value (local 'method')

### ISSUE THREAD

**Issue by jgarte** [fischerling/vis-lspc#21]
I get the following error when trying to use references `gr` with pyls

```
/home/jgart/.config/vis/plugins/vis-lspc/init.lua:755: attempt to call a string value (local 'method')
```

**Comment by fischerling** [comment]
Sorry for that.
I had uncommitted changes fixing this on my system.
Just pushed them as 37ef27177133eca24254e278d37497b5842f18fd.

**Comment by jgarte** [comment]
Thanks! I'll pull the your new changes in.
