### ISSUE TITLE
Give an option to choose between fzf and skim

### ISSUE THREAD

**Issue by jgarte** [fischerling/vis-lspc#22]
This works, for example:

```
-- check if skim is available and use skim instead of vis-menu per default
if os.execute('type sk >/dev/null 2>/dev/null') then
  lspc.menu_cmd = 'sk'
end
```

WDYT?

Maybe we can have a config global or something for setting between fzf and [skim](https://github.com/lotabout/skim)?

Or, is it a trivial enough change that the user can just set it themselves?

I wonder if [fzy](https://github.com/jhawthorn/fzy) works...

**Comment by fischerling** [comment]
> This works, for example:
> 
> ```
> -- check if skim is available and use skim instead of vis-menu per default
> if os.execute('type sk >/dev/null 2>/dev/null') then
>   lspc.menu_cmd = 'sk'
> end
> ```

That is the expected way to configure it.

> WDYT?
> 
> Maybe we can have a config global or something for setting between fzf and [skim](https://github.com/lotabout/skim)?
> 
> Or, is it a trivial enough change that the user can just set it themselves?


There are currently yo configuration option changing the programms used to get any user input.

	* `menu_cmd = 'fzf' or 'vis-menu'` - program to prompt for user choices
	* `confirm_cmd = 'vis-menu'` - program to prompt for user confirmation

I do not see what a global variable would do. Set both?

In my opinion the configuration is documented and trivial enough to
keep it as it is.

**Comment by jgarte** [comment]
> In my opinion the configuration is documented and trivial enough to keep it as it is.

I agree! Hadn't looked at `menu_cmd` yet. I'll close this.
