### ISSUE TITLE
ccls: init.lua:773: attempt to index a nil value (local 'result')

### ISSUE THREAD

**Issue by jgarte** [fischerling/vis-lspc#23]
! was trying out [ccls](https://github.com/MaskRay/ccls) and I get the following error when I open a c file:
```
/home/jgart/.config/vis/plugins/vis-lspc/init.lua:773: attempt to index a nil value (local 'result')
```

This is what is in `init.lua` that I added:

```
local ccls = {name = 'ccls', cmd = 'ccls'}

...

lspc.ls_map = {python = pyls, ansi_c = ccls}
```

**Comment by jgarte** [comment]
Here's the debug output also if that helps:

```
LSPC Sending: Content-Length: 181

{"params":{"processID":14165, "capabilities":{"workspace":{"configuration":false}}, "client":{"name":"vis-lspc", "version":"0.1.3"}}, "method":"initialize", "jsonrpc":"2.0", "id":0}
LS response(STDOUT): Content-Length: 77

{"jsonrpc":"2.0","id":0,"error":{"code":-32600,"message":"expected rootUri"}}
LSPC Error: expected rootUri (-32600) occurred during initialize call
```

**Comment by fischerling** [comment]
That is because the `rootUri` parameter in the initialize call is optional and we currently do not support workspaces.
See https://microsoft.github.io/language-server-protocol/specification.html#initialize

Maybe you could try clangd. Thats what I use for C and it works without issues at least on my system :)

**Comment by fischerling** [comment]
Did you see an error message before the crash?

**Comment by fischerling** [comment]
https://github.com/fischerling/vis-lspc/blob/37ef27177133eca24254e278d37497b5842f18fd/init.lua#L753-L758

Should have shown the error returned from ccls.

**Comment by fischerling** [comment]
b08f3bfbb0428aba83968d3339e12c7e29d7997a should fix the crash and only show you the error message.

**Comment by jgarte** [comment]
> That is because the `rootUri` parameter in the initialize call is optional and we currently do not support workspaces. See https://microsoft.github.io/language-server-protocol/specification.html#initialize

Maybe, I can try implementing `rootUri`. Is that a feature that is not in vis-lspc for a particular reason or just because no one has worked on it?

> 
> Maybe you could try clangd. Thats what I use for C and it works without issues at least on my system :)

How do you usually install clangd?

I'm thinking of packaging it for guix. 

ccls is already in guix and I just upgraded it:

https://issues.guix.gnu.org/52017

**Comment by fischerling** [comment]
https://github.com/MaskRay/ccls/wiki/FAQ#project-root-detection

**Comment by jgarte** [comment]
> clangd is part of the clang package on Arch.

Oh ok, it's the same on guix (bundled with clang). I just checked. `guix install clang`

Does clangd support the c language also?

I'll open an issue to ask if `ccls` can support clients not capable of a workspace first before trying to work on this.

**Comment by fischerling** [comment]
> Does clangd support the c language also?

clangd is used in the vis-lspc default config for ansi_c and cpp so yes.
I use it both for cpp and C.

And it works also for projects not buildable with clang (linux for example).
It only needs a .compile_commands.json database.

Which is generated by modern build systems or by using [bear](https://github.com/rizsotto/Bear) and make.

> I'll open an issue to ask if `ccls` can support clients not capable of a workspace first before trying to work on this.

**Comment by fischerling** [comment]
Moved to [https://gitlab.com/muhq/vis-lspc/-/issues/23](https://gitlab.com/muhq/vis-lspc/-/issues/23).
