### ISSUE TITLE
C-k conflicts with vis' (create count new selections on the lines above)

### ISSUE THREAD

**Issue by jgarte** [fischerling/vis-lspc#26]
https://github.com/fischerling/vis-lspc/blob/master/bindings.lua#L59

https://github.com/martanne/vis/blob/1a958f221404b09cb8b0612fb34301e6b9783cf9/config.def.h#L185

**Comment by fischerling** [comment]
Thanks, good catch!
I copied most of the bindings from the [neovim lsp client](https://github.com/neovim/nvim-lspconfig#keybindings-and-completion) without checking for conflicts.

Do you have a suggestion for a new help signature keybinding?

**Comment by jgarte** [comment]
> Thanks, good catch! I copied most of the bindings from the [neovim lsp client](https://github.com/neovim/nvim-lspconfig#keybindings-and-completion) without checking for conflicts.
> 
> Do you have a suggestion for a new help signature keybinding?

I don't have a preference yet. I "cc'd" [ninewise](https://github.com/ninewise/dotfiles) who started using `vis-lspc` recently to see if they might want to make a suggestion.

What language server have you successfully used that function/feature with? I don't think I was able to use it successfully with the python language server.

**Comment by ninewise** [comment]
I've changed it to `<C-K>` (rather than `<C-k>`), but that's just because I don't need signature help. I'm mostly in to this for the completion and jump-to's.

**Comment by jgarte** [comment]
@fischerling Here's what helix does if you want some extra inspirartion: https://docs.helix-editor.com/keymap.html

**Comment by fischerling** [comment]
> @fischerling What language server have you successfully used `lspc-signature-help` with? I don't think I was able to use it successfully with the python language server.

With ff92a0f1fca0f0db5b00022fc2ac41579ac5ab24 I can use signatureHelp with pyls.
In the screenshot my cursor is on line 6 column 15 inside the parameters of the foo call.
![screenshot](https://user-images.githubusercontent.com/1218430/144824295-7af4eb06-e0d1-4931-9ef6-35e2a267a8a4.png)

**Comment by fischerling** [comment]
I think I will remap it like ninewise to <C-K>.

**Comment by fischerling** [comment]
Fixed by 05a623879af0137b0a42693d89a206f7dfd97d32.
