### ISSUE TITLE
vis fork that comes bundled with vis-lspc and communication API patches applied

### ISSUE THREAD

**Issue by jgarte** [fischerling/vis-lspc#27]
@fischerling WDYT of creating a vis fork that comes bundled with `vis-lspc` and `communication` API patches already applied?

I think this would be convenient for people to use lsp with vis "out of the box".

I'd be willing to help out.

I'm thinking here of the way [helix](https://helix-editor.com/) or vscode comes with lsp. No need to install a plugin.

**Comment by fischerling** [comment]
Hm I think I would prefer the communicate API to be merged upstream.
Because I have another plugin `vis-spellcheck` that could also benefit from having this patchset applied.

I am not willing to maintain such a fork but I would contribute. Help bundling my stuff in a way that it works.

But I am not sure if a convenient out-of-the box experience is what people want when choosing
vis as their editor. Vis advertises it self as hackable and is aimed at people seeking
either a small, but full-powered vi-like editor or want to customize and hack their editor experience.
Therefore I am not sure if such an fork would have any audience.
But if someone does it I see myself contributing and possible packaging it for the AUR.

**Comment by jgarte** [comment]
> Hm I think I would prefer the communicate API to be merged upstream. Because I have another plugin `vis-spellcheck` that could also benefit from having this patchset applied.

Do you think martanne would accept the communicate API patch into vis?

> 
> I am not willing to maintain such a fork but I would contribute. Help bundling my stuff in a way that it works.

I'm considering starting a fork so I'll let you know when/if I get around to it.

Maybe the `configure` script can have a flag to choose between building vis with or without vis-lspc...

`--without-lsp`


> But I am not sure if a convenient out-of-the box experience is what people want when choosing vis as their editor. Vis advertises it self as hackable and is aimed at people seeking either a small, but full-powered vi-like editor or want to customize and hack their editor experience. Therefore I am not sure if such an fork would have any audience. 

I agree with this sentiment. WDYT of the `--without-lsp` option I mentioned above?

> But if someone does it I see myself contributing and possible packaging it for the AUR.

I'd like to put it in a custom guix channel and/or [carbslinux](https://carbslinux.org/) repo.

Those are the two distro projects I'm most involved with at the moment.

**Comment by fischerling** [comment]
> > Hm I think I would prefer the communicate API to be merged upstream. Because I have another plugin `vis-spellcheck` that could also benefit from having this patchset applied.
> 
> Do you think martanne would accept the communicate API patch into vis?

No idea. The PR is around for quite some time. But martanne has not responded as far as I know. Maybe someone should ping and ask him on irc.

> I agree with this sentiment. WDYT of the `--without-lsp` option I mentioned above?

But why would someone use a fork of vis with extra goodies and than decide to
configure it without those? Could the person not use normal vis in the first place?

So you would you guard the patch behind a preprocessor define or apply the patch with the configure script?
How do we distribute vis-lspc? With the default visrc in `/usr/share/vis`? Maybe `/usr/share/vis/plugins`?
And load it if `vis:communicate` is available in lua?

**Comment by jgarte** [comment]
I added a vis package with communication API applied to this Guix channel:

https://git.sr.ht/~whereiseveryone/guixrus/tree/master/item/guixrus/packages/suckless-forks.scm#L122

See README for channel usage. Feel free to start your own channel if this proves convenient.

I'm planning to add vis-lspc as an input to `vis-lsp` package and then adding a custom phase for vendoring it in. Guile/guix can handle that 

I think this could be one way to create a vis-lsp package without having to maintain a fork or vis or vis-lspc.

**Comment by fischerling** [comment]
> I think this could be one way to create a `vis-lsp` guix package without having to maintain a fork or `vis` and/or `vis-lspc`. I can just pull in the various sources and assemble them with guile/guix.
> 

Guix is neat I have to give it another try some day.

> @fischerling Should I be pulling in the sources from your `communicate` branch instead of xomachine's tree?
> 
> xomachine's tree still builds fine.

I don't know mine is rebased onto current master but I am sure that I will not
update it if vis master changes (except I randomly notice or someone pings me).
Maybe it is better to use original tree.
I am still hoping that those get eventually merged upstream.

**Comment by jgarte** [comment]
@fischerling 

Just wanted to let you know that I was able to bundle `vis-lspc` with vis in the guix package I made.

Here is the relevant code in case you're interested.

Where I pull in the `vis-lspc` sources:

https://git.sr.ht/~whereiseveryone/guixrus/tree/master/item/guixrus/packages/suckless-forks.scm#L270

Here is where I actually install `vis-lspc` in this `bundle-vis-lspc` phase:

https://git.sr.ht/~whereiseveryone/guixrus/tree/master/item/guixrus/packages/suckless-forks.scm#L296

all best

**Comment by fischerling** [comment]
Guile or any scheme dialect looks so alien to me :D

Congratulations! Great that it works.

Should we close this issue and mention the guix channel and vis-lsp in the README?

**Comment by jgarte** [comment]
> Guile or any scheme dialect looks so alien to me :D
> 
> Congratulations! Great that it works.
> 
> Should we close this issue and mention the guix channel and vis-lsp in the README?

Thanks! 

Sure, I can make a pull request for that. Closing this issue.

**Comment by mcepl** [comment]
Could you take a look at https://github.com/martanne/vis/issues/988, please? It seems to me that [the communicate patch](https://github.com/martanne/vis/pull/675) may be the culprit.

**Comment by fischerling** [comment]
> Could you take a look at [martanne/vis#988](https://github.com/martanne/vis/issues/988), please? It seems to me that [the communicate patch](https://github.com/martanne/vis/pull/675) may be the culprit.

I am using vis with only the patches from martanne/vis#675 rebased onto master for a long time now and have never experienced any crash.

**Comment by mcepl** [comment]
I think I found an error in my rebasing of that patch on the current master (I have commented on the pull request). Sorry for the false positive.
