### ISSUE TITLE
texlab completion

### ISSUE THREAD

**Issue by jgarte** [fischerling/vis-lspc#28]
Do you happen to know why completion does not work with [texlab](https://github.com/latex-lsp/texlab)?

**Comment by fischerling** [comment]
For me completions using texlab work without an issue.
I tested it right know using texlab 3.1.1 available in arch linux.

**Comment by jgarte** [comment]
It must be that the texlab in void linux is broken. Let me test the one packaged in `nixpkgs`.

**Comment by jgarte** [comment]
Ok confirmed texlab is working! void package is broken. I installed from nixpkgs.
