### ISSUE TITLE
Feature Request: Specify menu command dynamically from command mode

### ISSUE THREAD

**Issue by jgarte** [fischerling/vis-lspc#29]
# Proposal

I think it would be useful to be able to specify the menu command dynamically from vis' command mode.

## Documentation

```
lspc-menu-cmd <command> - Use <command> to prompt for user choices
```

## Examples

```
:lspc-menu-cmd sk
```

```
:lspc-menu-cmd fzf
```
```
:lspc-menu-cmd vis-menu
```

etc...

WDYT?

**Comment by fischerling** [comment]
I think this should be an configuration option.

```
:set vis-menu-cmd sk
```

Does #30 what you want?

**Comment by jgarte** [comment]
> I think this should be an configuration option.
> 
> ```
> :set vis-menu-cmd sk
> ```
> 
> Does #30 what you want?

LGTM, Awesome!
