### ISSUE TITLE
json implementation language

### ISSUE THREAD

**Issue by jgarte** [fischerling/vis-lspc#31]
Would it be possible to use a json implementation in another language?

What possibilities were you thinking about when you wrote [the json implementation of your choice](https://github.com/fischerling/vis-lspc#requirements)?

I imagine someone could implement one in fennel or idris-lua that compiles to lua.

Just brainstorming/thinking aloud

**Comment by fischerling** [comment]
> Would it be possible to use a json implementation in another language?

In C yes, any language that compiles to lua I think so too, anything else I don't know.

> What possibilities were you thinking about when you wrote [the json implementation of your choice](https://github.com/fischerling/vis-lspc#requirements)?

I was searching for a json implementation in lua and found multiples
so I decided to use any present one if available and ship a fallback.

Vis-lspc will try to get a json implementation using `require('json')` if the user
has one installed or the system has a global one that will be used instead
of the fallback json implementation bundled with vis-lspc.

So if a fennel based json implementation is available in your vis' lua environment
then vis-lspc will happily use that.

But it must provide `encode` and `decode`.

**Comment by fischerling** [comment]
See:
https://github.com/fischerling/vis-lspc/blob/c60f7f44aad12382cb55057339277d7f3db8e9a8/init.lua#L14-L27

**Comment by mcepl** [comment]
Well, I was wondering whether it would be possible to use either lua-cjson or lua-dkjson. I am a packager for openSUSE, so it is not a problem to make the vis package dependent on either of these two, but they don’t provide `json` module, but these are called `cjson` or `dkjson` respectively.

**Comment by fischerling** [comment]
> Well, I was wondering whether it would be possible to use either lua-cjson or lua-dkjson. I am a packager for openSUSE, so it is not a problem to make the vis package dependent on either of these two, but they don’t provide `json` module, but these are called `cjson` or `dkjson` respectively.

Hm so what would be the ideal solution for openSUSE?
Just check `cjson` and `dkjson` as well or should we make the string used to load the json implementation user configurable?
Or introduce a environment variable?

**Comment by mcepl** [comment]
Well, `cjson` seems to be more widely used (e.g., neovim bundles it), so just add some kind of `try .. except` construct checking for availability of `cjson` before settling down on `json`?

**Comment by fischerling** [comment]
Does 655dafe59e35a2bc7bd0785c342c47e3ea860c70 what you want?
We now try 'json', 'cjson', 'dkjson' in that order before using the bundled fallback.

**Comment by mcepl** [comment]
That’s absolutely awesome! Thank you!

**Comment by fischerling** [comment]
Moved to [https://gitlab.com/muhq/vis-lspc/-/issues/31](https://gitlab.com/muhq/vis-lspc/-/issues/31).
