### ISSUE TITLE
Docs and guide

### ISSUE THREAD

**Issue by erf** [fischerling/vis-lspc#9]
I'm new to LSP, but as i understand this implementation let's `vis` talk to various language servers via the un-merged `vis:communicate` addition, as to provide more features, like autocomplete and go to reference etc, and this plugin in itself does not extend any features, but rather you'd have to download and run servers mentioned in #2 for your specific language to work with these extensions, is that correct? 

Maybe some info on how LSP works and  a guide on how to get up and running with some languages could be added?

**Comment by fischerling** [comment]
> I'm new to LSP, but as i understand this implementation let's `vis` talk to various language servers via the un-merged `vis:communicate` addition, as to provide more features, like autocomplete and go to reference etc, and this plugin in itself does not extend any features, but rather you'd have to download and run servers mentioned in #2 for your specific language to work with these extensions, is that correct?

Yes absolutely correct.

> Maybe some info on how LSP works and a guide on how to get up and running with some languages could be added?

It is indeed also for me the first time dealing with language servers. I just knew that they exist for various languages.
I used [Microsoft's LSP website](https://microsoft.github.io/language-server-protocol/overviews/lsp/overview/) during the implementation.

What Information do you think would be valuable for you?
* Clarification that vis-lspc is not enough and need a language server to work?
* Link to a list of language servers?
* Information about how to configure a language server for vis-lspc (Some information are available in #2)

**Comment by erf** [comment]
I think that might help. Maybe we could add a install guide per language or a Lua Plugin per language which would help with the install / configure process?

**Comment by fischerling** [comment]
Ideally the user must only install the language server they want and vis-lspc
comes already configured to be used with the language server.
This is why #2 exists, to collect all the command line arguments and language servers
people actually use with vis-lspc.

**Comment by erf** [comment]
Ah i see. That's cool. Hope vis:communicate will be merged, that'll make it easier, but not sure martanne have decided on the server / client solution.

**Comment by fischerling** [comment]
I pushed 7a573b4e45e30c1f3f3a3828371ee61cd14dfb1e which adds more information about language server configuration to the README.
Do you think the additional information is understandable and usefull?

**Comment by erf** [comment]
That's great! I like the example also. I'll close this now.

BTW. Is it not possible that the correct language server will auto-start for the current file type?

**Comment by fischerling** [comment]
> BTW. Is it not possible that the correct language server will auto-start for the current file type?

Yes it is.
If `autostart` is set in the table returned by `require('vis-lspc') which is `true` by default vis-lspc will try to automatically start the language server for the current file.
